# Generated by Django 3.0.1 on 2020-03-21 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rotinew', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='roti',
            new_name='rotii',
        ),
        migrations.RenameField(
            model_name='rotii',
            old_name='user',
            new_name='userw',
        ),
        migrations.RenameField(
            model_name='rotii',
            old_name='value',
            new_name='valuew',
        ),
    ]
